kuma:
  image: louislam/uptime-kuma:2.1.3-rootless
  port: 3001
  servicePort: 3001

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false

  env:
    DB_TYPE: mariadb
    DB_HOST: mariadb
    DB_PORT: 3306
    DB_NAME: kuma_db
    DB_USER: kuma_user
    DB_PASSWORD: kuma123
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"

mariadb:
  image: mariadb:11.4

  securityContext:
    runAsUser: 999
    runAsGroup: 999
    runAsNonRoot: true
    allowPrivilegeEscalation: false

  env:
    MYSQL_ROOT_PASSWORD: root123
    MYSQL_DATABASE: kuma_db
    MYSQL_USER: kuma_user
    MYSQL_PASSWORD: kuma123
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

persistence:
  kuma:
    size: 1Gi
    storageClass: "nfs-netapp-01"
  mariadb:
    size: 5Gi
    storageClass: "nfs-netapp-01"